/* Generated by Yosys 0.49+10 (git sha1 18a7c0038, x86_64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "template.v:32.1-47.10" *)
module template(i_clk, i_reset_n, i_data, o_data);
  (* src = "template.v:33.29-33.34" *)
  input i_clk;
  wire i_clk;
  (* src = "template.v:35.29-35.35" *)
  input [7:0] i_data;
  wire [7:0] i_data;
  (* src = "template.v:34.29-34.38" *)
  input i_reset_n;
  wire i_reset_n;
  (* src = "template.v:36.29-36.35" *)
  output [7:0] o_data;
  reg [7:0] o_data;
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[0] <= 1'h0;
    else o_data[0] <= i_data[0];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[1] <= 1'h0;
    else o_data[1] <= i_data[1];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[2] <= 1'h0;
    else o_data[2] <= i_data[2];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[3] <= 1'h0;
    else o_data[3] <= i_data[3];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[4] <= 1'h0;
    else o_data[4] <= i_data[4];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[5] <= 1'h0;
    else o_data[5] <= i_data[5];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[6] <= 1'h0;
    else o_data[6] <= i_data[6];
  (* src = "template.v:39.1-45.4" *)
  always @(posedge i_clk)
    if (!i_reset_n) o_data[7] <= 1'h0;
    else o_data[7] <= i_data[7];
endmodule
